Jij-Inc/Qamomile

- jijmodeling_transpiler_quantum/core/qrac/graph_coloring.py
- tests/test_qrac.py
The problem is caused by try to know the current max index of the quad term like the below code
```python
max_idx = max(color_group.keys()) 
```
This causes error when the `color_group` is empty, so I change this as below
```python
max_idx = max(color_group.keys()) if color_group else -1
```
When the dictionary is empty, -1 is returned. This is because we would like to start the linear term from the max index of the quad term, so the initial linear index should be 0, so I set the return value as -1.
> fix the issues #35

- README.md
- docs/index.md
- docs/overrides/gen_ref_pages.py
- docs/tutorial/alternating_ansatz_graph_coloring_qiskit.ipynb
- docs/tutorial/alternating_ansatz_graph_coloring_quri.ipynb
- jijmodeling-transpiler-quantum is still used in `gen_ref_pages.py`, so I fixed the name
- change import name in the example
> fix name jijmodeling-transpiler-quantum to qamomile in documents

- qamomile/core/converters/qrao/qrao21.py
- qamomile/core/converters/qrao/qrao31.py
- qamomile/core/ising_qubo.py
- tests/test_ising_qubo.py
- tests/test_qrao.py
This PR mainly makes two corrections and one addition.
The items to be corrected are as follows.
1. Correction of the coefficients of (3,1)-QRAO. Since 3 and $\sqrt{3}$ were missing, they were added.
2. When linear or quad of `IsingModel` is empty, an error occurred in `max` when calling `num_bits`.
The additions are
1. (2,1)-QRAO functionality has been added.
> Add (2,1)-QRAO and fix the coefficient of (3,1)-QRAO

- qamomile/core/converters/qaoa.py
- qamomile/core/operator.py
- qamomile/qiskit/transpiler.py
- tests/qiskit/test_transpiler.py
- tests/test_operator.py
- tests/test_qrao.py
- I have introduced addition and multiplication to the `Hamiltonian`.
- The return values of `X(idx)`, `Y(idx)`, and `Z(idx)` have been changed to the `Hamiltonian` class.
- Fixed a bug in the conversion to qiskit Hamiltonian.
- I have introduced `Pauli.I`.
```python
import qamomile.core.operator as qm_o
x0 = qm_o.X(0)
h1 = 2.0 * x0 + 1.0
h = h1 * h1 # 4x0 + 5.0
expected_h = qm_o.Hamiltonian()
expected_h.constant += 5.0
expected_h.add_term((qm_o.PauliOperator(qm_o.Pauli.X, 0),), 4.0)
assert h == expected_h
```
> Introduction of addition and multiplication to the Hamiltonian

- .github/workflows/jupyter-book-publish.yml
- docs/_config.yml
The github link on the Document site was still pointing to the jupyter book, so I changed it to point to Qamomile.
And also, fix the installation of qamomile.
> fix the repository link in the docs

- qamomile/core/converters/qrao/qrao31.py
- tests/test_qrao.py
When creating the Hamiltonian for QRAO, the order used was X, Y, Z, so the operators used in (2,1)-QRAO were X and Y, which was different from the paper.
To fix this, the order of the operators used was changed to Z, X, Y, and it was made consistent with the paper.
In addition, the documentation was also incorrect, so it was corrected.
> Fixing the order of operators when creating a QRAO Hamiltonian

- qamomile/core/converters/qrao/qrao31.py
- qamomile/core/converters/qrao/qrao_space_efficient.py
- tests/test_qrao.py
I have implemented Space Efficient QRAO.
And, fix the `offset` in the `qrao31` and `qrao21`
> add Space Efficient QRAO

- qamomile/core/converters/qrao/qrao32.py
- qamomile/core/operator.py
- tests/test_32qrao.py
- tests/test_operator.py
I have implemented Space Efficient QRAO.
And, add `__sub__` for `Hamiltonian`
```python
import jijmodeling as jm
import jijmodeling_transpiler.core as jmt
from qamomile.core.converters.qrao.qrao32 import QRAC32Converter
problem = jm.Problem("sample")
x = jm.BinaryVar("x", shape = (3,))
problem += x[1] * x[2] + x[0]
compiled_instance = jmt.compile_model(problem, {})
converter = QRAC32Converter(compiled_instance)
cost_hamiltonian = converter.get_cost_hamiltonian()
pauli_list = converter.get_encoded_pauli_list()
```
> add (3,2)-QRAO

- qamomile/core/bitssample.py
- tests/qiskit/test_transpiler.py
- tests/quri_parts/test_quri_transpiler.py
- tests/test_bitssample.py
fix #64
I have reversed the interpretation of bitstring
```python
bitarray = list(map(int, bin(int_value)[2:].zfill(bit_length)[::-1]))
```
> Fix interpretation of bit order

- qamomile/core/bitssample.py
- qamomile/core/converters/converter.py
- qamomile/core/converters/qaoa.py
- qamomile/core/ising_qubo.py
- tests/qiskit/test_transpiler.py
- tests/quri_parts/test_quri_parameter_converter.py
- tests/quri_parts/test_quri_transpiler.py
- tests/test_32qrao.py
- tests/test_ising_qubo.py
This PR changes the default value of `simplify` to `False` in the `qubo_to_ising` to prevent index mismatches between QUBO and Ising models caused by simplification.
Modified the default value of `simplify` parameter in `qubo_to_ising` from `True` to `False`.
This change helps avoid index mismatches that occur when simplifying the Ising model, which can lead to incorrect results when using var_map.
This is a quick fix. 
A more comprehensive solution is needed to ensure correct indexing even when `simplify=True`. This will be addressed in a future update.
#66
> Set Default `simplify` to False in `qubo_to_ising`

- qamomile/quri_parts/transpiler.py
- tests/quri_parts/test_quri_transpiler.py
This fixes issue #69.
We should use [SinglePauli index](https://quri-parts.qunasys.com/api/quri_parts/core/quri_parts.core.operator.pauli.html#quri_parts.core.operator.pauli.SinglePauli) which is 1,2 or 3for `pauli_ids` in `add_ParametricPauliRotation_gate`.
This indexing is not same as `Pauli` in Qamomile.
> fix quri transpile for prametricTwoQubitGate

- qamomile/core/converters/qaoa.py
The cost function coefficients were $\beta$ and the mixer coefficients were $\gamma$, but I swapped the gamma and beta to match the Farhi’s original paper.
Therefore, I set the cost function coefficient to $\gamma$ and the mixer coefficient to $\beta$.
> Swap the names of QAOA parameters

- README.md
- docs/contribute.md
- docs/index.md
The link to contribution guide was broken.
Please look at first commit. cee1936bd596209a1f94c3131711eea5bc606659
In `contribute.md`, sample command to clone forked repository locally is `gh repo clone Jij-Inc/Qamomile`.
It clones the original repository, so I sugesste to change `Jij-Inc` to something else.
In my commit, it is changed to `username` for now. 6b42d3986bd7f9dee456785a8358c81ef4a2958b
I'm not very familiar with GitHub, so I'm sorry if there are any mistakes.
Thank you:)
> docs: Fix typos and suggest changes to example commands in documentation

- qamomile/core/converters/converter.py
Add `normalize_model` option to `QuantumConverter` class and pass it to `jmt.pubo.transpile_to_pubo`
This change introduces the `normalize_model=False` argument to the` __init__` in the `QuantumConverter` class, allowing the normalization of mathematical models to be toggled on or off based on user input. 
Additionally, the argument `normalize = normalize_model` is now passed to the `jmt.pubo.transpile_to_pubo`[function](https://github.com/Jij-Inc/JijModelingTranspiler/blob/main/jijmodeling_transpiler/core/pubo/to_pubo.py)
```
import jijmodeling_transpiler.core as jmt
import qamomile.core as qm
converter = qm.qaoa.QAOAConverter(compiled_instance, normalize_model=True)
```
> Add new argument normalize_model

- qamomile/core/circuit/circuit.py
- tests/core/circuit/test_circuit.py
allowed float type as angle argument in all the parametric gates
1. added the following code in all the types inside `ParametricSingleQubitGate` and `ParametricTwoQubitGate` in `circuit.py`
```
if isinstance(angle, float):
angle = Parameter(angle)
```
2. added a corresponding test in `test_circuit.py` 
#92
> allowed float type in all the parametric gates

- qamomile/core/operator.py
- tests/core/test_operator.py
Fixed a bug where the num_qubits information would disappear after the calculation, even though `h = Hamiltonian(num_qubits=3)`.
The `__add__` and `__mul__` of `Hamiltonian` now inherit the information before the operation.
In addition, when performing an operation on two Hamiltonians, the one with the larger num_qubits is selected to be inherited.
> fix num_qubits when add and multiply Hamiltonian

- qamomile/core/circuit/drawer.py
Support `ParametricExpGate` by `plot_quantum_circuit`.
I have fixed `plot_quantum_circuit` since `ParametricExpGate` could not be displayed.
```python
import qamomile.core.operator as qm_o
import qamomile.core.circuit as qm_c
from qamomile.core.circuit.drawer import plot_quantum_circuit
hamiltonian = qm_o.Hamiltonian()
hamiltonian += 5.0 * qm_o.X(0) * qm_o.Z(3) -4 * qm_o.Y(0) * qm_o.Y(1)
qc = qm_c.QuantumCircuit(5)
theta = qm_c.Parameter(r"\theta")
qc.exp_evolution(theta,hamiltonian)
hamiltonian = qm_o.Hamiltonian()
hamiltonian += -qm_o.X(2) * qm_o.Z(4) -  qm_o.Y(2) * qm_o.Y(4)
qc.exp_evolution(theta,hamiltonian)
plot_quantum_circuit(qc)
```
> support exp gate for circuit drawer

- qamomile/core/operator.py
- tests/core/test_operator.py
The original code 
```python
math.isclose(other.constant, 0.0, abs_tol=1e-15)
```
is only acceptable for real value.
However, we should accept complex value as coefficient of Hamiltonian.
So, I modified this part as
```python
math.isclose(abs(other.constant), 0.0, abs_tol=1e-15)
```
> fix `is_close` calculation in operator

- docs/references.bib
- qamomile/core/converters/converter.py
- qamomile/core/ising_qubo.py
- tests/core/test_ising_qubo.py
I introduce the Ising Hamiltonian normalization to `IsingModel`.
I have implemented two types of the normalization called, `rms` and `abs_max`.
The detail explanation is in the docstring of `normalize_by_abs_max` and `normalize_by_rms` in `ising_qubo,py`.
However, I have chosen that we did not normalize Ising Hamiltonian as default because changing the default value breaks the behavior of the old version.
You can access this option through `QuantumConverter`.
This is the example code
```python
normalize_ising = "rms"
qaoa_converter = qm.qaoa.QAOAConverter(compiled_instance, normalize_ising=normalize_ising)
```
I have done two benchmarks.
So far, I feel that `abs_max` works better than the other method.
I define the problem as follows:
```python
N = 16
J = np.random.randn(N,N)
J = (J + …
```
> Introduce to Ising Hamiltonian normalization

- .github/workflows/jupyter-book-publish.yml
- docs/qamomile-lp/src/components/Explore/Explore.jsx
- docs/qamomile-lp/src/components/Header/Header.jsx
Fix some wrong URLs in documentation pages and Enable `jupyter-notebook-publish`. Thus, the new documentation pages will be published once this PR is merged.
> Enable jupyter-notebook-publish

- qamomile/core/operator.py
Fix the bugs pointed out in #157.
The code
```python
import qamomile.core.operator as qm_o
h = qm_o.Hamiltonian()
h._terms = {
(qm_o.PauliOperator(qm_o.Pauli.I, 0),): 1.0,
(qm_o.PauliOperator(qm_o.Pauli.X, 0),): 1.0,
(qm_o.PauliOperator(qm_o.Pauli.I, 0),): 1.0,
}
print(h.to_latex())
```
returns
```bash
X_{0}
```
Close #157 once this PR is merged.
> Fix `to_latex` to work with `Pauli.I`

- qamomile/core/ising_qubo.py
Remove `calc_qubo_energy` since the reason that is written in #179 . I took the first option, removing the function itself. If anyone thinks the second option is better, please let me know that.
Close #179 once this PR is merged.
> Remove `calc_qubo_energy` function

- qamomile/core/converters/converter.py
- qamomile/core/ising_qubo.py
- tests/core/converters/test_32qrao.py
- tests/core/converters/test_qrao.py
- tests/core/test_ising_qubo.py
- Move `qubo_to_ising` to `IsingModel` as class method in `core/ising_qubo.py` and rename it as `from_qubo`.
- Replace `qubo_to_ising` with `IsingModel.from_qubo` in files that were used `qubo_to_ising`.
Close #178 once this PR is merged.
> Move `qubo_to_ising` to `IsingModel` as class method

- LICENSE.txt
- README.md
This PR adds the Apache 2.0 license to the Qamomile repository as LICENSE.txt.
This addresses the missing license file in the repository.
> Add Apache 2.0 license
